# Generated by Django 5.2.18 on 2026-10-07 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('setor', models.CharField(max_length=60)),
                ('marca', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('community', models.CharField(default='public', max_length=60, verbose_name='SNMP community')),
                ('ativa', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=True)),
                ('ultima_coleta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.CharField(blank=True, max_length=200)),
                ('contador_paginas', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'impressoras',
                'ordering': ['setor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='modelo do toner')),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('ciano', 'Ciano'), ('magenta', 'Magenta'), ('amarelo', 'Amarelo'), ('outro', 'Outro')], default='preto', max_length=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=2)),
                ('impressoras', models.ManyToManyField(blank=True, related_name='toners', to='toner.impressora')),
            ],
            options={
                'verbose_name': 'modelo de toner',
                'verbose_name_plural': 'modelos de toner',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('ciano', 'Ciano'), ('magenta', 'Magenta'), ('amarelo', 'Amarelo'), ('outro', 'Outro')], default='outro', max_length=10)),
                ('percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('atualizado', models.DateTimeField(blank=True, null=True)),
                ('alertado', models.BooleanField(default=False)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suprimentos', to='toner.impressora')),
            ],
            options={
                'ordering': ['cor', 'nome'],
                'unique_together': {('impressora', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('suprimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='toner.suprimento')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('automatica', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='toner.impressora')),
                ('suprimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.suprimento')),
                ('toner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.modelotoner')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'trocas',
                'ordering': ['-data'],
            },
        ),
    ]
